config/routes.rb
Rails.application.routes.draw do
  post   'email/',      to: 'email#create',  as: 'emails'
  get    'email/new',   to: 'email#new',     as: 'new_email'
  delete 'email/',      to: 'email#delete',  as: 'delete'
  get    'email/email_list'
  get    'email/user_list'

  get    'admin/' => 'admin#index', :as => :admin
  post   'admin/' => 'admin#new', :as => :new_user
  delete 'admin/' => 'admin#destroy', :as => :delete_user

  get    'reset_salesforce/' => 'salesforce#reset_salesforce', :as => :reset_salesforce
  post   'reset_salesforce/' => 'salesforce#save_password', :as => :save_password

  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/controllers/salesforce_controller.rb
class SalesforceController < ApplicationController
  include SalesforceClient

  before_action :ensure_sign_in

  def reset_salesforce
    begin
      connect_salesforce
    rescue
      authorize current_user, :edit?
    else
      flash[:notice] = "Your Salesforce password is already up to date."
      redirect_to new_email_path
    end
  end

  def save_password
    begin
      connect_salesforce
    rescue
      authorize current_user, :edit?
      @password = params[:password][:password]
      @confirm_password = params[:confirm_password][:confirm_password]
      @security_token = params[:token][:token]
      if @password == @confirm_password
        ENV['SALESFORCE_PASSWORD'] = @password
        ENV['SALESFORCE_SECURITY_TOKEN'] = @security_token
        flash[:notice] = "Salesforce password successfully updated."
      end
    ensure
      @after_sign_in_url = root_path
      render 'partials/_callback', :layout => false
    end
  end
end

app/views/salesforce/reset_salesforce.html.haml
- content_for(:head) do
  = stylesheet_link_tag 'reset_sf', '//fonts.googleapis.com/css?family=Montserrat:400,700'

%body#reset_body
  %h1 Reset Salesforce Password
  = form_tag save_password_path do

    = label :password, :password, "Enter New Password"
    = text_field :password, 'password', :class => "form-control"

    = label :confirm_password, :confirm_password, "Confirm New Password"
    = text_field :confirm_password, 'confirm_password', :class => "form-control"

    =label :token, :token, "Enter New Security Token"
    = text_field :token, 'token', :class => "form-control"

    = submit_tag "Save", :class => "btn btn-lg"